### ISSUE TITLE
Plugin crashes if node module has "." in name

### ISSUE THREAD

**Issue by mattoni** [Jimdo/typings-for-css-modules-plugin#16]
I'm attempting to import a node module, "highlight.js", but this causes the typed css plugin to crash with the following error:

```
TypeError: Path must be a string. Received undefined                                                                        
    at assertPath (path.js:7:11)                                                                                            
    at Object.extname (path.js:1429:5)    
    at isCssModule               
```

Ideally, the plugin would only work on ones with common css, scss etc extensions.

**Comment by mattoni** [comment]
Looks like there was a separate issue involved where the package hadn't installed correctly.
